### ISSUE TITLE
Can you create an additional config file so that the server admin can choose which boss bags can be claimed by players

### ISSUE THREAD

**Issue by Hex4gonForc3** [Soof4/Bagger#4]

**Comment by LiteralSoofa** [comment]
When i add #1, that will be possible. (I've got exams in the near future so you need to wait for at least 2 weeks.)

**Comment by Hexagonforce12** [comment]
Ok

**Comment by LiteralSoofa** [comment]
With bd12038 (v1.1.0), this can be achieved by changing the stack value of a drop in the config file to 0.

**Comment by Hexagonforce12** [comment]
OK, thank you for making it
